services:
  client-dev:
    build:
      context: .
      dockerfile: apps/client-web/Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - ./apps/client-web/src:/app/apps/client-web/src
      - ./packages/shared-core/src:/app/packages/shared-core/src
      - ./packages/shared-protocol/src:/app/packages/shared-protocol/src
    environment:
      - VITE_API_URL=http://localhost:4000
